version: "3.8"
services:
  db:
    image: mysql:8.2
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
    volumes:
      - ./data/db:/var/lib/mysql
  nginx:
    build: ./nginx
    volumes:
      - '../public:/app/public'
    ports:
      - '${NGINX_PORT}:80'
    depends_on:
      - app
  app:
    build: ./app
    volumes:
      - '..:/app'
    env_file:
      - .env
    environment:
      XDEBUG_MODE: debug,coverage
      XDEBUG_SESSION: PHPSTORM
