parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/Constant/'
            - '../src/Dto/'
            - '../src/Entity/'
            - '../src/Enum/'
            - '../src/Exception/'
            - '../src/Request/'
            - '../src/Response/'
            - '../src/Util/'
            - '../src/Kernel.php'

    App\Controller\:
        resource: '../src/Controller/'
        tags: [ 'controller.service_arguments' ]
